version: "3.8"

services:
  mcp-server:
    build: .
    container_name: mcp-claude-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Servicio opcional para desarrollo con hot-reload
  mcp-dev:
    build: .
    container_name: mcp-claude-dev
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
