version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/openapi.json
    volumes:
      - ./openapi.json:/app/openapi.json
    depends_on:
      - api
